components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /Auth:
    get:
      tags:
        - Auth-managment
      description: All endpoints releated to auth
      summary: All endpoints releated to auth
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema: 
                type: string